baseURL = "https://www.arnavion.dev/"
languageCode = "en-us"
title = "www.arnavion.dev"
disableHugoGeneratorInject = true
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm"]

[blackfriday]
nofollowLinks = true
smartypants = false

[outputs]
home = ["HTML"]
blog = ["HTML", "RSS"]
